//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Albums1 = new HashSet<Album>();
        }
    
        public string Title { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Genre { get; set; }
        public int ArtistId { get; set; }
        public int Id { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Album> Albums1 { get; set; }
    }
}
