-- MySQL Script generated by MySQL Workbench
-- 08/31/14 12:06:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BooksDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BooksDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BooksDB` ;

-- -----------------------------------------------------
-- Table `BooksDB`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BooksDB`.`Authors` (
  `idAuthor` INT NOT NULL,
  `authorName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BooksDB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BooksDB`.`Books` (
  `idBook` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `publishDate` DATE NULL,
  `ISBN` VARCHAR(45) NULL,
  `Authors_idAuthor` INT NOT NULL,
  PRIMARY KEY (`idBook`),
  INDEX `fk_Books_Authors_idx` (`Authors_idAuthor` ASC),
  CONSTRAINT `fk_Books_Authors`
    FOREIGN KEY (`Authors_idAuthor`)
    REFERENCES `BooksDB`.`Authors` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
